### ISSUE TITLE
Eigen moved or deleted

### ISSUE THREAD

**Issue by lorddaha** [whitfijs-jw/Volvo240-DigitalDash#49]
**Describe the bug**
The folder declared for eigen pointer has either been moved or deleted, needed to manually download eigen package and put into that folder

Should be an easy fix

**Comment by whitfijs-jw** [comment]
Hi!

Make sure you clone the repository and all of the submodules:

I did a quick test using this command and everything was in place:
`git clone git@github.com:whitfijs-jw/Volvo240-DigitalDash.git --recurse-submodules`

If you already cloned the repository you can fetch the submodules after the fact.
```
git clone git@github.com:whitfijs-jw/Volvo240-DigitalDash.git
git submodule init
git submodule update
```

Let me know if this works out for you.

**Comment by whitfijs-jw** [comment]
Haven't heard back so I'm closing this for now.  Feel free to create another bug or start a discussion.
